export const UPLOAD_RECIPE_REQUEST = "UPLOAD_RECIPE_REQUEST";
export const UPDATE_RECIPE_REQUEST = "UPDATE_RECIPE_REQUEST";
export const GET_RECIPES_REQUEST = "GET_RECIPES_REQUEST";
export const GET_RECIPE_REQUEST = "GET_RECIPE_REQUEST";
export const SET_RECIPES = "SET_RECIPES";
export const SET_RECIPE = "SET_RECIPE";
