export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const SET_PROFILE = "SET_PROFILE";
export const SET_DELETED_RECIPE = "SET_DELETED_RECIPE";
export const DELETE_RECIPES_REQUEST = "DELETE_RECIPES_REQUEST ";
export const SET_DELETED_SAVED_RECIPE = "SET_DELETED_SAVED_RECIPE";
export const DELETE_SAVED_RECIPES_REQUEST = "DELETE_SAVED_RECIPES_REQUEST";
